### ISSUE TITLE
Brainstorm Ideas

### ISSUE THREAD

**Issue by takuyakikuchi** [takuyakikuchi/tbd#1]
## Deliveries

- [x] Miro Mind Map
  - [x] What is App about
  - [x] Features
  - [x] Tech Stack

## Todos

- [x] Brain Storm
  - [x] What tools I want to use
  - [x] What features
- [x] Research What kind of app
  - [x] Search for interesting API
  - [x] Search for App idea

## References

- https://miro.com/app/board/uXjVOot3f_w=/

## Other notes

None
